/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as diamond from "./diamond";
export type { diamond };
import type * as ourkade from "./ourkade";
export type { ourkade };
