/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../common";

export interface NewfucInterface extends utils.Interface {
  functions: {
    "readRepGuiltyLimit()": FunctionFragment;
    "setRepGuiltyLimit(uint8)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "readRepGuiltyLimit" | "setRepGuiltyLimit"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "readRepGuiltyLimit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setRepGuiltyLimit",
    values: [PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "readRepGuiltyLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRepGuiltyLimit",
    data: BytesLike
  ): Result;

  events: {};
}

export interface Newfuc extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: NewfucInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    readRepGuiltyLimit(overrides?: CallOverrides): Promise<[number]>;

    setRepGuiltyLimit(
      _guiltylimit: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  readRepGuiltyLimit(overrides?: CallOverrides): Promise<number>;

  setRepGuiltyLimit(
    _guiltylimit: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    readRepGuiltyLimit(overrides?: CallOverrides): Promise<number>;

    setRepGuiltyLimit(
      _guiltylimit: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    readRepGuiltyLimit(overrides?: CallOverrides): Promise<BigNumber>;

    setRepGuiltyLimit(
      _guiltylimit: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    readRepGuiltyLimit(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setRepGuiltyLimit(
      _guiltylimit: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
