/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as newfucSol from "./newfuc.sol";
export type { newfucSol };
import type * as ourkadeAdminSol from "./ourkadeAdmin.sol";
export type { ourkadeAdminSol };
import type * as ourkadeCompetitionSol from "./ourkadeCompetition.sol";
export type { ourkadeCompetitionSol };
import type * as ourkadeGameSol from "./ourkadeGame.sol";
export type { ourkadeGameSol };
import type * as ourkadeHelperSol from "./ourkadeHelper.sol";
export type { ourkadeHelperSol };
import type * as ourkadeNodeSol from "./ourkadeNode.sol";
export type { ourkadeNodeSol };
import type * as ourkadePlayerSol from "./ourkadePlayer.sol";
export type { ourkadePlayerSol };
