/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as library from "./library";
export type { library };
import type * as ourkadeLogicContract from "./ourkadeLogicContract";
export type { ourkadeLogicContract };
