/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as newfucSol from "./newfuc.sol";
export * as ourkadeAdminSol from "./ourkadeAdmin.sol";
export * as ourkadeCompetitionSol from "./ourkadeCompetition.sol";
export * as ourkadeGameSol from "./ourkadeGame.sol";
export * as ourkadeHelperSol from "./ourkadeHelper.sol";
export * as ourkadeNodeSol from "./ourkadeNode.sol";
export * as ourkadePlayerSol from "./ourkadePlayer.sol";
